<option>administrator</option>
<option>artist</option>
<option>doctor</option>
<option>educator</option>
<option>engineer</option>
<option>entertainment</option>
<option>executive</option>
<option>healthcare</option>
<option>homemaker</option>
<option>lawyer</option>
<option>librarian</option>
<option>marketing</option>
<option>none</option>
<option>other</option>
<option>programmer</option>
<option>retired</option>
<option>salesman</option>
<option>scientist</option>
<option>student</option>
<option>technician</option>
<option>writer</option>